version: '3.8'

# -----------------------------------------------------------------------
# NOTE:
# run `docker network create --driver bridge salami-slicing-net`
# before running `docker-compose up -d` for the first time.
# 
# NOTE 2:
# For refreshing all the "latest" services versions use the following 
# sequence of commands:
#     docker-compose stop
#     docker-compose rm -f
#     docker-compose pull   
#     docker-compose up -d
# -----------------------------------------------------------------------

services:
  consul:
    image: consul:latest
    hostname: consul
    restart: always
    container_name: consul
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    volumes:
      - ./consul/config:/etc/consul.d
      - ./consul/data:/bitnami
  redis:
    image: bitnami/redis:latest
    hostname: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/bitnami/redis/data
    environment:
      - REDIS_HOSTS=local:redis:6379
      - ALLOW_EMPTY_PASSWORD=yes
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    container_name: redis-commander
    ports:
    - '8081:8081'
    environment:
    - REDIS_HOSTS=redis
    restart: always
    depends_on:
      - redis

